# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('file_name', models.CharField(max_length=50, unique=True)),
                ('key', models.CharField(max_length=512, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
