# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 21:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypt_my_cloud', '0002_file_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='allowed_user',
            field=models.ManyToManyField(related_name='shared_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
